CREATE TABLE source_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_id TEXT NOT NULL UNIQUE,
    content_id TEXT NOT NULL,
    hxs_version INTEGER NOT NULL CHECK (hxs_version = 1),
    game_version TEXT NOT NULL,
    language TEXT NOT NULL,
    scope TEXT NOT NULL CHECK (scope = 'full'),
    extractor_version TEXT NOT NULL,
    lumina_version TEXT NOT NULL,
    sheet_count BIGINT NOT NULL CHECK (sheet_count >= 0),
    row_count BIGINT NOT NULL CHECK (row_count >= 0),
    string_cell_count BIGINT NOT NULL CHECK (string_cell_count >= 0)
);

CREATE INDEX idx_source_snapshots_content ON source_snapshots(content_id);

CREATE TABLE source_sheets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_db_id BIGINT NOT NULL REFERENCES source_snapshots(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    variant SMALLINT NOT NULL CHECK (variant IN (0, 1)),
    effective_language TEXT NOT NULL,
    column_count BIGINT NOT NULL CHECK (column_count >= 0),
    row_count BIGINT NOT NULL CHECK (row_count >= 0),
    schema_hash BYTEA NOT NULL CHECK (octet_length(schema_hash) = 32),
    technical_hash BYTEA NOT NULL CHECK (octet_length(technical_hash) = 32),
    string_hash BYTEA NOT NULL CHECK (octet_length(string_hash) = 32),
    content_hash BYTEA NOT NULL CHECK (octet_length(content_hash) = 32),
    UNIQUE (snapshot_db_id, name)
);

CREATE INDEX idx_source_sheets_snapshot ON source_sheets(snapshot_db_id);

CREATE TABLE source_columns (
    sheet_id BIGINT NOT NULL REFERENCES source_sheets(id) ON DELETE CASCADE,
    column_index INTEGER NOT NULL CHECK (column_index >= 0),
    offset BIGINT NOT NULL,
    type TEXT NOT NULL,
    PRIMARY KEY (sheet_id, column_index)
);

CREATE TABLE source_rows (
    sheet_id BIGINT NOT NULL REFERENCES source_sheets(id) ON DELETE CASCADE,
    row_id BIGINT NOT NULL CHECK (row_id BETWEEN 0 AND 4294967295),
    subrow_id INTEGER NOT NULL CHECK (subrow_id BETWEEN 0 AND 65535),
    row_hash BYTEA NOT NULL CHECK (octet_length(row_hash) = 32),
    technical_hash BYTEA NOT NULL CHECK (octet_length(technical_hash) = 32),
    string_hash BYTEA NOT NULL CHECK (octet_length(string_hash) = 32),
    PRIMARY KEY (sheet_id, row_id, subrow_id)
);

CREATE INDEX idx_source_rows_sheet ON source_rows(sheet_id);

CREATE TABLE source_string_cells (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sheet_id BIGINT NOT NULL,
    row_id BIGINT NOT NULL,
    subrow_id INTEGER NOT NULL,
    column_index INTEGER NOT NULL CHECK (column_index >= 0),
    macro_text TEXT NOT NULL,
    macro_hash BYTEA NOT NULL CHECK (octet_length(macro_hash) = 32),
    raw_hash BYTEA CHECK (raw_hash IS NULL OR octet_length(raw_hash) = 32),
    FOREIGN KEY (sheet_id, row_id, subrow_id)
        REFERENCES source_rows(sheet_id, row_id, subrow_id) ON DELETE CASCADE,
    UNIQUE (sheet_id, row_id, subrow_id, column_index)
);

CREATE INDEX idx_source_string_cells_row ON source_string_cells(sheet_id, row_id, subrow_id);
