package com.harmoniasuite.source.domain;

public enum SourceUploadErrorCode {
    INTERNAL_FAILURE,
    STAGING_MISSING,
    STAGING_CLEANUP_FAILED,
    TRANSPORT_HASH_FAILURE,
    HXS_TOO_LARGE,
    DECOMPRESSION_FAILED,
    SIZE_MISMATCH,
    ATLAS_VERIFICATION_FAILED,
    METADATA_MISMATCH,
    MATERIALIZATION_FAILED,
    ARTIFACT_STORAGE_FAILED
}
